{% set name = "sqlalchemy_schemadisplay" %}
{% set version = "1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d9a815dc6b411d519805c056c40ba7448f3572e9abdfbf9c246f7a37e7b1afc

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pydot
    - python >={{ python_min }}
    - sqlalchemy

test:
  requires:
    - python {{ python_min }}
  imports:
    - sqlalchemy_schemadisplay

about:
  home: https://github.com/fschulze/sqlalchemy_schemadisplay
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Turn SQLAlchemy DB Model into a graph
  dev_url: https://github.com/fschulze/sqlalchemy_schemadisplay

extra:
  recipe-maintainers:
    - lincrosenbach
    - igorcandeia
    - nicoddemus
