{% set name = "sqlalchemy_schemadisplay" %}
{% set version = "2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e90b9c9868814975d674a889aadb7c4651658f0e119e1c9320279ea527744d5e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - flit-core >=3.4,<4
  run:
    - pydot
    - python >=3.8
    - sqlalchemy >=2.0,<3

test:
  imports:
    - sqlalchemy_schemadisplay

about:
  home: https://github.com/fschulze/sqlalchemy_schemadisplay
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Turn SQLAlchemy DB Model into a graph
  dev_url: https://github.com/fschulze/sqlalchemy_schemadisplay

extra:
  recipe-maintainers:
    - lincrosenbach
    - igorcandeia
    - nicoddemus
